default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'zazz_development') %>
  host:     <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', '') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  port:     <%= ENV.fetch('POSTGRES_PORT', 5432) %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'zazz_test') %>
  host:     <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  port:     <%= ENV.fetch('POSTGRES_PORT', 5432) %>


staging: &staging_default
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production: *staging_default
